### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by ericdrosado** [AsyncBanana/microdiff#29]
👋 Hi @AsyncBanana,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX. 

You mentioned in your submission that you wanted to submit a `Collaborate` repo. This means that you want to invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a `Collaborate` CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch. 

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated. 

I look forward to working with you :octocat: 

## Issues
- [x] https://github.com/AsyncBanana/microdiff/issues/30
- [x] https://github.com/AsyncBanana/microdiff/issues/31
- [x] https://github.com/AsyncBanana/microdiff/issues/32

**Comment by AsyncBanana** [comment]
Hello! Thanks for helping me with this! I will take a look at these and see what I can do.

**Comment by ericdrosado** [comment]
👋 Hi @AsyncBanana ! I noticed you didn't submit your repo in [CX](https://education.github.com/globalcampus/exchange). Are you no longer interested in participating?

**Comment by AsyncBanana** [comment]
Sorry about that, I have submitted it now.

**Comment by ericdrosado** [comment]
Thank you @AsyncBanana for contributing! 

I wish you and your project the best. Cheers!
